### ISSUE TITLE
Weird syntax highlight with dark theme

### ISSUE THREAD

**Issue by Zilkos** [oltd/dose#2]
Hi ! 

First, thank you for your theme (and for not using Google Font or any CDN stuff <3).

I really like your dark theme but code blocks highlighting stings the eyes, because of white background : 

<img width="980" alt="image" src="https://user-images.githubusercontent.com/19567823/145879827-2d960dde-f3e9-454f-84b6-13990721a321.png">

Does the futur toggle for white/dark mode will take into consideration this syntax highlight for code block or inline code ?

Cheers !

**Comment by oltdaniel** [comment]
Hi,

Thanks for the feedback. That really does not look that nice, especially the part of burning everyones eyes.

I have multiple options that would fix this:
1. Excluding the code blocks from the invert filter (like the images).
2. Moving from an CSS invert filter to actual theme colors, for example with CSS variables.

Both should have only a small impact on the CSS size and would allow users of the theme to have consistent syntax highlightning themes accross light and dark mode. 

Additionally, option 2 would allow emojies to render in zhe correct color, which I would prefer.

What's your opinion on this?

**Comment by Zilkos** [comment]
I am not very familiar with web development but I think that solution 2 is quite well. User will be able to modify those variables and customize as he wants (if he wants to set a custom highlight_theme value which fit better for example) AND have correct emojis.

My skills are weak (like my English 😃) but I can test you solution by grabbing a test branch if needed.

Thank you for your help.

**Comment by oltdaniel** [comment]
@Zilkos I justes implemented an fix in https://github.com/oltdaniel/dose/commit/70d54fe47825b7d761c57e58df6687c3548c5954 . Now we use colors instead of the invert mode, which means we don't have weird color shifts.

**Comment by Zilkos** [comment]
Awesome ! 

<img width="532" alt="image" src="https://user-images.githubusercontent.com/19567823/147365979-69019739-3f3e-421c-8dd6-3d794d36ab52.png">

**Comment by oltdaniel** [comment]
@Zilkos I fixed a little bug that occured, the time element for the main page listing was invisible in the dark mode. Fix can be found in commit https://github.com/oltdaniel/dose/commit/a1a567401590e5330b6117e7181415dfda64754e.
