### ISSUE TITLE
Reason: Filter truncate was called on an incorrect value: got null but expected a String #1

### ISSUE THREAD

**Issue by whoizit** [oltd/dose#3]
I have same issue, maybe you can fix it for your theme?
https://github.com/lukehsiao/zola-pickles/issues/1

**Comment by oltdaniel** [comment]
Done. Check the latest commit https://github.com/oltdaniel/dose/commit/8a6d82da7f18b839fd4bc8160fb3b5f0488867de .

**Comment by whoizit** [comment]
still happens. Problem in page.html

**Comment by oltdaniel** [comment]
Check https://github.com/oltdaniel/dose/commit/1bf9a27a230846fe9d14167c5ca750ce549b1ce4 .

**Comment by whoizit** [comment]
thank you!

**Comment by oltdaniel** [comment]
You could've made a pull request as well. No magic behind an if statement.
